import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'

import Breno from '../public/images/breno.svg'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Breno Lapreza - Desenvolvedor Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <div className="container main-container">
          <div>
            <h3>Olá 🖖, eu sou</h3>
            <h1>BRENO<br />LAPREZA</h1>
            <h2>DESENVOLVEDOR WEB</h2>
            <p>Tenho 21 anos. Moro no interior de São Paulo. Gosto muito de desenvolver, aprender e práticar.<br /> Sou desenvolvedor Web, clique e veja sobre os meus trabalhos 😃</p>
          </div>

          <div>
            <Image src={Breno} />
          </div>

        </div>
      </main>


    </div>
  )
}
